module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        heading: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'fine': ['11px', { lineHeight: '1.4', letterSpacing: '0.04em', fontWeight: '500' }],
        'caption': ['13px', { lineHeight: '1.5', letterSpacing: '0.01em' }],
        'body': ['15px', { lineHeight: '1.65' }],
        'body-lg': ['17px', { lineHeight: '1.65' }],
        'h3': ['22px', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '-0.01em' }],
        'h2': ['30px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '-0.015em' }],
        'h1': ['42px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'display': ['56px', { lineHeight: '1.08', fontWeight: '700', letterSpacing: '-0.03em' }],
      },
      borderRadius: {
        'xs': '0.2rem',
        'sm': '0.35rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        'studio': '0.75rem 2rem 0.75rem 2rem',
        'studio-sm': '0.5rem 1.25rem 0.5rem 1.25rem',
        'studio-lg': '1rem 3rem 1rem 3rem',
        'studio-xs': '0.35rem 0.9rem 0.35rem 0.9rem',
        'full': '9999px',
      },
      boxShadow: {
        'studio': '0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.03), inset 0 1px 0 rgba(255,255,255,0.6)',
        'studio-lg': '0 4px 16px rgba(0,0,0,0.04), 0 2px 8px rgba(0,0,0,0.03), inset 0 1px 0 rgba(255,255,255,0.6)',
        'studio-hover': '0 8px 30px rgba(0,0,0,0.06), 0 2px 8px rgba(0,0,0,0.04), inset 0 1px 0 rgba(255,255,255,0.6)',
        'studio-glow': '0 0 0 1px rgba(196,101,74,0.1), 0 0 20px rgba(196,101,74,0.06), 0 1px 3px rgba(0,0,0,0.04)',
        'studio-colored': '0 4px 12px rgba(196,101,74,0.12), 0 1px 3px rgba(0,0,0,0.04)',
        'studio-inner': 'inset 0 1px 2px rgba(0,0,0,0.04), inset 0 0 0 1px rgba(0,0,0,0.02)',
      },
      colors: {
        primary: 'rgb(var(--color-primary-rgb) / <alpha-value>)',
        'primary-hover': 'rgb(var(--color-primary-hover-rgb) / <alpha-value>)',
        'primary-muted': 'rgb(var(--color-primary-muted-rgb) / <alpha-value>)',
        accent: 'rgb(var(--color-accent-rgb) / <alpha-value>)',
        'accent-hover': 'rgb(var(--color-accent-hover-rgb) / <alpha-value>)',
        background: 'rgb(var(--color-background-rgb) / <alpha-value>)',
        surface: 'rgb(var(--color-surface-rgb) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--color-surface-elevated-rgb) / <alpha-value>)',
        'surface-subtle': 'rgb(var(--color-surface-subtle-rgb) / <alpha-value>)',
        border: 'rgb(var(--color-border-rgb) / <alpha-value>)',
        'border-strong': 'rgb(var(--color-border-strong-rgb) / <alpha-value>)',
        'text-primary': 'rgb(var(--color-text-primary-rgb) / <alpha-value>)',
        'text-secondary': 'rgb(var(--color-text-secondary-rgb) / <alpha-value>)',
        'text-tertiary': 'rgb(var(--color-text-tertiary-rgb) / <alpha-value>)',
        success: 'rgb(var(--color-success-rgb) / <alpha-value>)',
        'success-hover': 'rgb(var(--color-success-hover-rgb) / <alpha-value>)',
        'success-muted': 'rgb(var(--color-success-muted-rgb) / <alpha-value>)',
        error: 'rgb(var(--color-error-rgb) / <alpha-value>)',
        'error-hover': 'rgb(var(--color-error-hover-rgb) / <alpha-value>)',
        'error-muted': 'rgb(var(--color-error-muted-rgb) / <alpha-value>)',
        warning: 'rgb(var(--color-warning-rgb) / <alpha-value>)',
        info: 'rgb(var(--color-info-rgb) / <alpha-value>)',
        overlay: 'rgb(var(--color-overlay-rgb) / <alpha-value>)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-4px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(4px)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '33%': { transform: 'translateY(-12px) rotate(1deg)' },
          '66%': { transform: 'translateY(-6px) rotate(-0.5deg)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        breathe: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        scalePress: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(0.97)' },
          '100%': { transform: 'scale(1)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
        slideUp: 'slideUp 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
        scaleIn: 'scaleIn 0.35s cubic-bezier(0.16, 1, 0.3, 1)',
        shake: 'shake 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
        slideDown: 'slideDown 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        float: 'float 8s ease-in-out infinite',
        shimmer: 'shimmer 2s linear infinite',
        breathe: 'breathe 3s ease-in-out infinite',
        scalePress: 'scalePress 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}